---
- hosts: localhost
  connection: local
  sudo: yes
  roles:
    - terminal
    - sivel.sshpass
    - devbox.chrome
    - geerlingguy.git
    - geerlingguy.composer
    - geerlingguy.java
    - grafics
    - filezilla
    - virtualbox
    - vagrant
    - mysql_wb
    - skype
