---

- name: Check if Google apt file exist.
  command: test -f {{apt_file}}
  register: google_apt_exists
  ignore_errors: True

- name: Add Google Chrome key
  shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  when: google_apt_exists.rc == 1

- name: Add Google Chrome repo
  copy:
    content: "deb http://dl.google.com/linux/chrome/deb/ stable main"
    dest: {{apt_file}}
    owner: root
    group: root
    mode: 0644
  when: google_apt_exists.rc == 1

- name: Update apt cache
  apt: update_cache=yes
  when: google_apt_exists.rc == 1

- name: Install Google Chrome
  apt: pkg=google-chrome-stable state=installed

- name: Download FlashPlugin
  get_url:
    url: '{{ flashplugin_url }}'
    dest: '{{ flashplugin_deb_path }}'
    mode: '0777'
  ignore_errors: True

- name: Check if the downloaded file exist
  stat:
    path: '{{ flashplugin_deb_path }}'
  register: flashplugin_file

- name: Install FlashPlugin from file
  apt:
    deb: '{{ flashplugin_deb_path }}'
  when: flashplugin_file.stat.exists == true
  sudo: yes

- name: Remove FlashPlugin .deb file
  file:
    path: '{{ flashplugin_deb_path }}'
    state: absent
  when: flashplugin_file.stat.exists == true